environment: development
host: 127.0.0.1
port: 3000
redis:
  host: 127.0.0.1
  port: 6379
  user:
  password:
  database: 0
routes:
  face:
    default_overlay: true
    default_download: false
    default_scale: 4
    min_scale: 1
    max_scale: 64
  head:
    default_overlay: true
    default_download: false
    default_scale: 4
    min_scale: 1
    max_scale: 64
  full_body:
    default_overlay: true
    default_download: false
    default_scale: 4
    min_scale: 1
    max_scale: 64
  front_body:
    default_overlay: true
    default_download: false
    default_scale: 4
    min_scale: 1
    max_scale: 64
  back_body:
    default_overlay: true
    default_download: false
    default_scale: 4
    min_scale: 1
    max_scale: 64
  left_body:
    default_overlay: true
    default_download: false
    default_scale: 4
    min_scale: 1
    max_scale: 64
  right_body:
    default_overlay: true
    default_download: false
    default_scale: 4
    min_scale: 1
    max_scale: 64
  raw_skin:
    default_download: false
cache:
  skin_cache_duration: 12h # 12 hours
  render_cache_duration: 12h # 12 hours
  enable_locks: true